# Generated by Django 5.2.16 on 2026-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('waste_category', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('recyclable', models.BooleanField()),
                ('bin', models.CharField(max_length=100)),
                ('recycling_instructions', models.TextField()),
                ('reuse_ideas', models.TextField()),
                ('environmental_impact', models.TextField()),
                ('image', models.ImageField(upload_to='detections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
